### ISSUE TITLE
Can't start minecraft client...

### ISSUE THREAD

**Issue by Thy20222** [Tutorials-By-Kaupenjoe/Fabric-Tutorial-1.21.X#6]
This is not an issue (just asking questions):
I'm following the tutorial.
Currently in the first episode.
And my game can't start, this is the error report:
Uncaught exception in thread "main"
java.lang.RuntimeException: Minecraft game provider couldn't locate the game! The game may be absent from the class path, lacks some expected files, suffers from jar corruption or is of an unsupported variety/version.
	at net.fabricmc.loader.impl.launch.knot.Knot.createGameProvider(Knot.java:212)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

**Comment by HealerPlusMC** [comment]
go to Gradle tab, Open Tasks Open Fabric Open RunClient

**Comment by kittykatstyle** [comment]
I'm also having the same issue with launching the game from IntelliJ

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command 'C:\Users\dk228\AppData\Local\Programs\Eclipse Adoptium\jdk-21.0.5.11-hotspot\bin\java.exe'' finished with non-zero exit value 1

**Comment by B1azeS1mple** [comment]
same issue "finished with non-zero exit value -1"

**Comment by HealerPlusMC** [comment]
Can you give me a Screenshot
